image: alpine

stages:
  - deploy

deploy_to_server:
  stage: deploy
  before_script:
    - "command -v ssh-agent >/dev/null || ( apk add --no-cache --update openssh )"
    - eval $(ssh-agent -s)

    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$HOST 'echo "Successfully connected to the server"'
