image: alpine

stages:
  - deploy

deploy_to_server:
  stage: deploy
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - cp $DEPLOY_KEY ~/.ssh/id_deploy_key
    - chmod 600 ~/.ssh/id_deploy_key
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
    - cat ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST 'echo "Successfully connected to the server"'
