#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate --no-input
python manage.py collectstatic --no-input

# execute the provided command (from the 'command' property in Docker Compose)
exec "$@"
