log:
  level: INFO

entryPoints:
  web:
    address: ":80"

  web-secure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: reeduoft@gmail.com
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
      #httpChallenge:
        # used during the challenge
        # entryPoint: web

http:
  routers:
    to-tomcat:
      rule: Host(`{{env "TRAEFIK_HOST"}}`)
      service: tomcat
      tls:
        certResolver: letsencrypt

    to-tomcat-admin:
      rule: Host(`{{env "TRAEFIK_HOST"}}`) && PathPrefix(`/admin`)
      middlewares:
        - basic-auth
      service: tomcat
      tls:
        certResolver: letsencrypt
      
    to-solr-admin:
      rule: Host(`{{env "TRAEFIK_HOST"}}`) && PathPrefix(`/solr`)
      middlewares:
        - basic-auth
      service: tomcat
      tls:
        certResolver: letsencrypt

    to-django:
      rule: Host(`{{env "TRAEFIK_HOST"}}`) && PathRegexp(`^/(accounts|djadmin|eats|geomap|prepare|selectable)/`)
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    to-nginx:
      rule: Host(`{{env "TRAEFIK_HOST"}}`) && PathRegexp(`^/(assets/|solr/|static/|robots.txt)`)
      middlewares:
        - csrf
      service: nginx
      tls:
        certResolver: letsencrypt

    redirect-ip:
      rule: "HostRegexp(`{host:(198\\.168\\.185\\.15)}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-domain
      service: noop@internal
      priority: 200

    redirect-ip-secure:
      rule: "HostRegexp(`{host:(198\\.168\\.185\\.15)}`)"
      entryPoints:
        - web-secure
      middlewares:
        - redirect-to-domain-secure
      service: noop@internal
      priority: 100
      tls: {}

    ip-to-domain:
      rule: "Host(`198.168.185.15`)"
      entryPoints:
        - web
      service: noop@internal
      priority: 1000
      middlewares:
        - to-domain

    http-to-https:
      rule: "Host(`ereed.org`) || Host(`www.ereed.org`) || Host(`dev.ereed.org`)"
      entryPoints:
        - web
      service: noop@internal
      priority: 100
      middlewares:
        - to-https

  middlewares:
    basic-auth:
      basicAuth:
        usersFile: /etc/traefik/.htpasswd

    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]
    
    redirect-to-domain:
      redirectRegex:
        regex: ".*"
        replacement: "https://ereed.org"
        permanent: true

    redirect-to-domain-secure:
      redirectRegex:
        regex: '^https://(198\.168\.185\.15)(/.*)?$'
        replacement: 'https://ereed.org$2'
        permanent: true

    to-domain:
      redirectRegex:
        regex: ".*"
        replacement: "https://ereed.org"
        permanent: true

    to-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    tomcat:
      loadBalancer:
        servers:
          - url: http://tomcat:8080

    django:
      loadBalancer:
        servers:
          - url: http://django:8000

    nginx:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: "/etc/traefik/traefik.yml"
    watch: true