log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ":443"
    http:
      middlewares:
        - redirect-to-domain

certificatesResolvers:
  letsencrypt:
    acme:
      email: reeduoft@gmail.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

http:
  routers:
    to-tomcat:
      rule: Host(`{{env "TRAEFIK_HOST"}}`)
      service: tomcat
      tls:
        certResolver: letsencrypt

    to-tomcat-admin:
      rule: Host(`{{env "TRAEFIK_HOST"}}`) && PathPrefix(`/admin`)
      middlewares:
        - basic-auth
      service: tomcat
      tls:
        certResolver: letsencrypt

    to-django:
      rule: Host(`{{env "TRAEFIK_HOST"}}`) && PathRegexp(`^/(accounts|djadmin|eats|geomap|prepare|selectable)/`)
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    to-nginx:
      rule: Host(`{{env "TRAEFIK_HOST"}}`) && PathRegexp(`^/(assets/|solr/|static/|robots.txt)`)
      middlewares:
        - csrf
      service: nginx
      tls:
        certResolver: letsencrypt

  middlewares:
    basic-auth:
      basicAuth:
        usersFile: /etc/traefik/.htpasswd

    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]
    
    redirect-to-domain:
      redirectRegex:
        regex: "^https?://198\.168\.185\.15/(.*)"
        replacement: "https://{{env "TRAEFIK_HOST"}}/$1"
        permanent: true

  services:
    tomcat:
      loadBalancer:
        servers:
          - url: http://tomcat:8080

    django:
      loadBalancer:
        servers:
          - url: http://django:8000

    nginx:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: "/etc/traefik/traefik.yml"
    watch: true
