# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-17 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0002_auto_20171130_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Place Type',
            },
        ),
        migrations.RemoveField(
            model_name='place',
            name='patrons_place_code',
        ),
        migrations.RemoveField(
            model_name='place',
            name='patrons_place_type',
        ),
        migrations.AddField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='patrons_label_flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Places not expected to be labelled'), (1, 'Places to be labelled at all zoom levels (eg, major towns)'), (2, 'Places to be labelled at intermediate zoom levels (eg, minor towns)'), (3, 'Places to be labelled at highest zoom levels (eg, buildings)')], null=True, verbose_name='label flag'),
        ),
        migrations.DeleteModel(
            name='PatronsPlaceType',
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='geomap.PlaceType'),
        ),
    ]
