# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='patrons_label_flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Local sites not expected to be labelled'), (1, 'Major town or place to be labelled at all zoom levels'), (2, 'Minor town or place to be labelled at intermediate zoom levels'), (3, 'Named performance venues to be labelled when zoomed in to largest scales')], null=True, verbose_name='P&P label flag'),
        ),
        migrations.AlterField(
            model_name='place',
            name='patrons_place_code',
            field=models.IntegerField(blank=True, choices=[(1, 'Town, known event'), (2, 'Residence, known event'), (3, 'Monastery, known event'), (4, 'Town, reference or major town'), (5, 'Residence, reference'), (6, 'Monastery, reference'), (7, 'Town, known local event'), (8, 'Residence, known local event'), (9, 'Monastery, known local event'), (10, 'Town, local reference to place'), (11, 'Residence, local reference to place'), (12, 'Monastery, local reference to place')], null=True, verbose_name='P&P PCODE'),
        ),
        migrations.AlterField(
            model_name='place',
            name='patrons_place_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='geomap.PatronsPlaceType'),
        ),
    ]
