# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0005_place_symbol_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='tile_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
